# Generated by Django 5.1.2 on 2024-11-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], max_length=10, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Pet')),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=10, verbose_name='Espécie')),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10, verbose_name='Porte')),
                ('cor', models.CharField(max_length=30, verbose_name='Cor')),
                ('detalhes', models.TextField(verbose_name='Detalhes')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email do usuário')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('rede_social', models.CharField(blank=True, max_length=100, verbose_name='Rede social principal')),
                ('image', models.ImageField(blank=True, upload_to='user_images/')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
        ),
    ]
