# Generated by Django 5.1.2 on 2024-11-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Tutor'),
        ),
        migrations.AddField(
            model_name='pet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='pet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='pet',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone do Tutor'),
        ),
        migrations.AddField(
            model_name='pet',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.usuario', verbose_name='Dono'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='detalhes',
            field=models.TextField(blank=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descrição do Local'),
        ),
    ]
