# Generated by Django 5.1.2 on 2024-12-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_senha_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
