# Generated by Django 5.1.2 on 2024-12-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pet_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.usuario', verbose_name='Dono'),
        ),
    ]
